name: Generate Trophies & Activity Graph

on:
  schedule:
    # runs daily at 18:00 UTC (23:30 IST)
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-trophy-and-activity-graph
    steps:
      - uses: actions/checkout@v5

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: rishijain544
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: rishijain544
          options: theme=tokyo-night&hide_border=true
          output_path: activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "update trophy & activity graph"; then git push; fi
